# Build the Docker image 
steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/myproject-406204/mahara-100944755/python-midterm:${COMMIT_SHA}', '.']

# Push the Docker image to the artifact registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/myproject-406204/mahara-100944755/python-midterm:${COMMIT_SHA}']

# Deploy the Docker container to Google Cloud Run in multiple regions
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'sh'
    args: 
      - '-c'
      - |
        gcloud run deploy python-app \
          --image=us-central1-docker.pkg.dev/myproject-406204/mahara-100944755/python-midterm:${COMMIT_SHA} \
          --platform=managed \
          --region=us-central1,us-east1 \
          --port=8080 \
          --allow-unauthenticated

# Deploy the messages to pub/sub topic, so that the developers can see it
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'pubsub'
      - 'topics'
      - 'publish'
      - 'projects/myproject-406204/topics/mahara-topic'
      - '--message'
      - 'Mahara Deployment is completed.'
 
options:
  defaultLogsBucketBehavior: 'REGIONAL_USER_OWNED_BUCKET'

images:
  - us-central1-docker.pkg.dev/myproject-406204/mahara-100944755/python-midterm:${COMMIT_SHA}
